from .collection import Collection
from .none import NoneCollection
from .aws import AWSCollection
from .input import InputCollection
from .payment import PaymentCollection
from .vpn import VPNCollection
from .social import SocialCollection
from .environment import EnvironmentCollection
from .login import LoginCollection
