from .collection import Collection
from .none import NoneCollection
from .aws import AWSCollection
from .input import InputCollection
from .payment import PaymentCollection
from .vpn import VPNCollection
from .social import SocialCollection
from .environment import EnvironmentCollection
from .login import LoginCollection
from .production import ProductionCollection
from .staging import StagingCollection
from .client import ClientCollection
from .brochure import BrochureCollection
from .auth import AuthCollection
from .owa import OWACollection
